### PR TITLE
Configure linters and analyzers and enable in CI

### PR DESCRIPTION
**Pull request by JPrevost**
Why are these changes being introduced:

* These tools are in line with our current Python practices to ensure
  consistent coding standards

Relevant ticket(s):

* https://mitlibraries.atlassian.net/browse/ETD-409

How does this address that need:

* Installs the tooling used and configures `make lint` to run them with
  our preferred settings for CI
* Updates files that were not compliant with the settings being
  introduced
* Configures GitHub Actions to run the expected linters and analyzers

Document any side effects to this change:

* Running tests is out of scope for this work as the application
  currently does not have any tests. When tests are added, CI will
  need to be updated to run them.

#### Includes new or updated dependencies?

YES

#### Changes expectations for external applications?

NO

#### Developer

- [x] All new ENV is documented in README
- [x] All new ENV has been added to staging and production environments
- [x] All related Jira tickets are linked in commit message(s)

#### How can a reviewer manually see the effects of these changes?

* run the related `make` tasks locally
* look at the output of the CI scripts in Actions

#### Code Reviewer

- [ ] The commit message is clear and follows our guidelines
      (not just this pull request message)
- [ ] There are appropriate tests covering any new functionality
- [ ] The documentation has been updated or is unnecessary
- [ ] The changes have been verified
- [ ] New dependencies are appropriate or there were no changes

### CODE REVIEW

**Comment by JPrevost** [comment]
Notes

* I have intentionally run each task separately in Actions rather than just `make lint` as it felt easier to see the output and determine which one was reporting problems when run this way.
* I used `.` as the path to run the tools against in each `make` task. If there is a reason to instead use the app directory and tests explicitly we can update that, but this seemed more copy / pasta-able for future work.

**Comment by ehanson8** [comment]
One note on using `.` with `bandit`, it doesn't like `assert` which we use frequently in our unit tests so we have it just scan the app directory and skip `tests`. I had originally used `.` for everything else in the `Makefile` and Helen suggested explicitly naming the folders, I didn't ask about her reasoning though

**Comment by JPrevost** [comment]
Feel free to add additional commits to get this in line with what the Python team would like in place and then go ahead and merge when it's ready. Thanks!

**Comment by hakbailey** [comment]
@ehanson8 this is ready for final review

**Pull request merged**
